server {
    listen 80;
    server_name _;

    include /etc/nginx/mime.types;
    types {
        application/javascript js mjs;
    }
    default_type application/octet-stream;

    root /usr/share/nginx/html;
    index index.html;

    location /assets/ {
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
